const data = {
    products: [
        {
            _id:'1',
            name:'Adidas Hoodies',
            category: 'Shirts',
            image:'/images/p1.jpg',
            price: 120,
            countInStock: 20,
            brand:'Adidas',
            rating: 5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Nike Fit Shirt',
            category: 'Shirts',
            image:'/images/p3.jpg',
            price: 110,
            countInStock: 12,
            brand:'Adidas',
            rating: 4.5,
            numReviews: 30,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Lacoste Pants',
            category: 'Pants',
            image:'/images/p2.jpg',
            price: 170,
            countInStock: 0,
            brand:'Adidas',
            rating: 3.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Adidas Hoodies',
            category: 'Shirts',
            image:'/images/p4.jpg',
            price: 220,
            countInStock: 25,
            brand:'Adidas',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Adidas Hoodies',
            category: 'Shirts',
            image:'/images/p1.jpg',
            price: 120,
            countInStock: 15,
            brand:'Adidas',
            rating: 5,
            numReviews: 20,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'Adidas Hoodies',
            category: 'Shirts',
            image:'/images/p1.jpg',
            price: 140,
            countInStock: 23,
            brand:'Adidas',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
    ]
}

export default data;