const data = {
    products: [
        {
            _id:'1',
            name:'Adidas Hoodies',
            category: 'Shirts',
            image:'/images/p1.jpg',
            price: 120,
            brand:'Adidas',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Nike Fit Shirt',
            category: 'Shirts',
            image:'/images/p2.jpg',
            price: 110,
            brand:'Adidas',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Lacoste Pants',
            category: 'Pants',
            image:'/images/p1.jpg',
            price: 120,
            brand:'Adidas',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Adidas Hoodies',
            category: 'Shirts',
            image:'/images/p1.jpg',
            price: 120,
            brand:'Adidas',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Adidas Hoodies',
            category: 'Shirts',
            image:'/images/p1.jpg',
            price: 120,
            brand:'Adidas',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'Adidas Hoodies',
            category: 'Shirts',
            image:'/images/p1.jpg',
            price: 120,
            brand:'Adidas',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
    ]
}

export default data;